version: '3'

services:
  reverse-proxy:
    image: traefik:v2.11
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.http.address=:80
      - --entrypoints.mysql.address=:3306
      - --providers.docker.exposedbydefault=true
    ports:
      - "80:80"
      - "8080:8080"
      - "3306:3306"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: course_catalog
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
        - ./api/database/migrations:/docker-entrypoint-initdb.d  # Mount migration scripts here
        - ./database/volume:/var/lib/mysql
    hostname: database.cc.localhost
    labels:
      - traefik.tcp.routers.mysql.entrypoints=mysql
      - traefik.tcp.routers.mysql.rule=HostSNI(`*`)
      - traefik.tcp.services.mysql.loadbalancer.server.port=3306

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - db
    volumes:
      - ./api/:/var/www/html/
    stdin_open: true
    tty: true
    hostname: api.cc.localhost
    ports:
      - "8081:80"
    labels:
      - traefik.http.routers.api.rule=Host(`api.cc.localhost`)
    environment:
      - DB_HOST=db
      - DB_USER=test_user
      - DB_PASSWORD=test_password
      - DB_NAME=course_catalog

  front:
    build:
        context: ./front_end/
        dockerfile: Dockerfile
    container_name: front
    depends_on:
      - api
    stdin_open: true
    tty: true
    hostname: cc.localhost
    labels:
      - traefik.http.routers.front.rule=Host(`cc.localhost`)
